### ISSUE TITLE
Long service restart

### ISSUE THREAD

**Issue by TheAndras** [detarkende/stremio-ncore-addon#3]
After a few days of use, the addon is already running several torrents. Unfortunately, it checks them all one by one on restart.
This is about 5-10 minutes per torrent, which is annoyingly long for 10-15 torrents.

It should work like any other torrent manager, check the files only if really necessary.

**Comment by detarkende** [comment]
@TheAndras please don’t close this issue until the connected MR is merged. 

Did the fix on the branch work?

**Comment by TheAndras** [comment]
Yes, it seems like it doing its job.
